default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: orders_api_development

test:
  <<: *default
  database: orders_api_test

production:
  <<: *default
  database: orders_api_production
  username: orders_api
  password: <%= ENV["ORDERS_API_DATABASE_PASSWORD"] %>
